version: "3.7"

services:

  app:
    build: ./
    container_name: userapp
    restart: always
    environment:
      - APP_NAME=ClientService
    ports:
      - "5000:5000"
    expose:
      - 5000
